### ISSUE TITLE
please consider to update example files

### ISSUE THREAD

**Issue by kmuto** [morgoth/picasa#35]
Because password authentication is abandoned by Google, most codes in examples directory won't work.
It would be really helpful if you brush up them modern style.

(I succeeded to get information from Picasa service+OAuth with your picasa.gem 0.8.0, but I can't succeed to upload a picture yet...)

**Comment by morgoth** [comment]
@kmuto In the meantime, you may take a look at https://github.com/morgoth/picasa#authentication how to obtain one time usage access token.
In all these examples, you just need to replace `:password => "password"` with `:access_token => "access-token-from-oauth"`

**Comment by jylitalo** [comment]
While the issue is closed, I just wanted to mention that I made blog post that might help @kmuto on options. You can find it from http://blog.ylitalot.com/2015/06/picasa-api-with-oauth2.html
Basically, if you are willing to use signet library and do little bit manual work to get refresh token for OAuth2 and store it for future use, you can still use picasa gem like it used to work with application passwords (with little extra help from signet). I still routinely upload my photos to Google+ with this gem.

**Comment by kmuto** [comment]
Thanks @morgoth and @jylitalo , my code works well now!

**Comment by morgoth** [comment]
@jylitalo Thanks for your investigation and blog post. It helped me to prepare short tutorial how to obtain `refresh_token` and use it to get `access_token` https://github.com/morgoth/picasa#permanent-server-side-usage
